### ISSUE TITLE
Handling Error 1006

### ISSUE THREAD

**Issue by ImTheDeveloper** [dirkbonhomme/pusher-client-node#16]
Hi,

I've recently seen that I hit the pusher error 1006:

```
Error { type: 'WebSocketError', error: 'close code 1006' }
```

I no longer seem to receive any messages after this event occurs so I took a look at the code and found that you've chosen not to handle this error with a retry:
https://github.com/dirkbonhomme/pusher-client-node/blob/master/lib/connection.js#L124
https://github.com/dirkbonhomme/pusher-client-node/blob/master/lib/connection.js#L128

I'm just wondering why this isn't included as part of the range you would like to retry on?

Also is there a way I can actively recover from such a disconnection?

Thanks

**Comment by dirkbonhomme** [comment]
Hmm good question. This node client is a port of the official Pusher JavaScript (client-side) library from a few years ago. They use the same handling of this code:
https://github.com/pusher/pusher-js/blob/0ef56995ed9605b79ba4b22d1a13c84652d47793/src/core/connection/protocol/protocol.ts#L95

The official library has since been rewritten and can now also be used in Node.js. If possible, try to switch to their library: https://github.com/pusher/pusher-js
It might have some retry logic for this error code these days.

**Comment by ImTheDeveloper** [comment]
Thanks I'll raise it with them although it seems to follow the same thinking.
